embedder:
  provider: "ollama"
  config:
    model: "nomic-embed-text"
    dimension: 384

long_term_memory:
  enabled: true
  external: true
  connection_string: "postgresql://postgres:your_password@localhost:5432/cognition_db"

short_term_memory:
  enabled: true
  external: true
  host: "localhost"
  port: 8000
  collection_name: "short_term"

entity_memory:
  enabled: true
  external: true
  host: "localhost"
  port: 8000
  collection_name: "entities"
